# fly.toml app configuration file generated for pop on 2023-05-11T19:10:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pop"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
